[package]
name = "food-rs"
version = "0.1.0"
authors = ["猫羽黑夜 <THE_cattail@k-neco.moe>"]
edition = "2021"
description = "Utilities for Rust programming by Cattail Magic Lab"
repository = "https://github.com/THE-cattail/food-rs"
license = "MIT"
keywords = ["utilities"]
categories = ["algorithms"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
log = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.9"
toml = "0.4"
