condense_wildcard_suffixes = true
enum_discrim_align_threshold = 20
error_on_line_overflow = true
error_on_unformatted = true
force_explicit_abi = false
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
match_block_trailing_comma = true
merge_derives = false
imports_granularity = "Crate"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
struct_field_align_threshold = 20
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
version = "Two"
wrap_comments = true